version: "3.1"

services:
  app:
    container_name: app
    image: snnkrmz/todo-backend-task1
    build: .
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/todo
      - SPRING_DATASOURCE_DB=todo
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=123
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE_URL=jdbc:postgresql://postgres_db:5432/todo
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  curl -X 'GET' 'http://localhost:8080/api/user'